version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://youruser:yourpassword@db:5432/yourdb?sslmode=disable
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: youruser
      POSTGRES_DB: yourdb
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"